root: true
env:
  browser: true
  es6: true
  node: true
extends: ["eslint:recommended"]
parser: "@babel/eslint-parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@babel"
  - react
  - react-hooks
rules:
  linebreak-style:
    - warn
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-unused-vars: 0
